name: "GitHub Action for red* OCaml packages"
description: "Workflow shared by all red* OCaml packages for building, testing, and documentation updates"
inputs:
  ocaml-compiler:
    description: "OCaml Compiler Version"
    required: true
  with-test:
    description: "Whether to test the package"
    required: false
    default: true
  with-doc:
    description: "Whether to build package documentation"
    required: false
    default: false
  publish-doc-if-built:
    description: "Whether to publish package documentation"
    required: false
    default: true
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: "Set up OCaml"
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ inputs.ocaml-compiler }}
    - name: "Fix OPAM repo for OCaml 5"
      if: ${{ inputs.ocaml-compiler == 'ocaml-variants.5.0.0+trunk' }}
      shell: sh
      run: opam repo add alpha git+https://github.com/kit-ty-kate/opam-alpha-repository.git --verbose
    - name: "Install the dependencies"
      shell: sh
      run: opam install ${{inputs.with-test == 'true' && '--with-test' || ''}} ${{inputs.with-doc == 'true' && '--with-doc' || ''}} --deps-only --yes --verbose .
    - name: "Build the package"
      shell: sh
      run: opam exec -- dune build
    - name: "Test the package"
      if: ${{ inputs.with-test == 'true' }}
      shell: sh
      run: opam exec -- dune runtest
    - name: "Build the documentation"
      if: ${{ inputs.with-doc == 'true' }}
      shell: sh
      run: opam exec -- dune build @doc
    - name: "Publish the documentation"
      if: ${{ inputs.with-doc == 'true' && inputs.publish-doc-if-built == 'true' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: "./_build/default/_doc/_html/"
